baseURL: https://status.garykim.dev
langaugeCode: en-US
title: garykim.dev Status Page
buildFuture: true

theme: cstate
preserveTaxonomyNames: true

taxonomies:
  affected: affected

canonifyurls: true
enableRobotsTXT: true
enableGitInfo: true

outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg

outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml

copyright: '<p>© 2020 Gary Kim &lt;<a href="mailto:gary@garykim.dev" rel="nofollow">gary@garykim.dev</a>&gt;</p>'

params:
  categories:
    - name: Gamma Server
      description: Services hosted on Gamma server
    - name: Sigma Server
      description: Services hosted on Sigma server
  systems:
    - name: "Minecraft: Turtle Server"
      category: Gamma Server
      description: "Minecraft: Turtle Server (mc.garykim.dev)"
    - name: "Minecraft: Cooper Union Modded Server"
      category: Gamma Server
      description: "Modded Minecraft server for Cooper Union students"
    - name: "Minecraft: Cooper Union Vanilla Server"
      category: Gamma Server
      description: "Vanilla Minecraft server for Cooper Union students"
    - name: "Proprietary Drone CI for GitHub"
      category: Gamma Server
      description: "Proprietary Drone CI instance connected to GitHub (https://ghdrone.garykim.dev)"
    - name: "Proprietary Drone CI for Personal Gitea Instance"
      category: Gamma Server
      description: "Proprietary Drone CI connected to personal Gitea instance (https://drone.garykim.dev)"
    - name: "garykim.dev Matrix Homeserver"
      category: Gamma Server
      description: "garykim.dev Matrix Homeserver (https://matrix.garykim.dev)"
    - name: "STUN/TURN Server"
      category: Gamma Server
      description: "STUN/TURN Server used by various services (turn.garykim.dev)"
    - name: "Grafana"
      category: Gamma Server
      description: "Grafana instance connected to various services (https://grafana.garykim.dev)"
    - name: "LibreOffice Online"
      category: Gamma Server
      description: "LibreOffice Online server used with various services. (https://office.garykim.dev)"
    - name: "Nextcloud Talk High Performance Backend"
      category: Gamma Server
      description: "Nextcloud Talk HPB connected to multiple Nextcloud instances (spreedbackend.garykim.dev)"
    - name: "Matterbridge Instance"
      category: Gamma Server
      description: "Matterbridge instance for syncing many different messaging systems"
    - name: "Gary Kim: Cloud"
      category: Gamma Server
      description: "Nextcloud (https://cloud.garykim.dev)"
  dateFormat: 2006-01-02T15:04:05Z07:00
  shortDateForamt: 2006-01-02T15:04:05Z07:00

  useLargeHeaderDesign: false
  useLogo: false

  description: Find out if there is any known downtime for garykim.dev services.

  disableComplexCalulations: false

  incidentPostsPerPage: 10

  brand: "#0a0c0f"
  ok: "#008000"
  disrupted: "#cc4400"
  down: "#e60000"
  notice: "#24478f"

  alwaysKeepBrandColor: true

  headerTextColor: white

  googleAnalytics: UA-00000000-1

  enableCustomHTML: true

